-- Create a table for public profiles
create table profiles (
  id uuid references auth.users not null primary key,
  updated_at timestamp with time zone,
  username text unique,
  full_name text,
  avatar_url text,
  website text,

  constraint username_length check (char_length(username) >= 3)
);

-- Set up Row Level Security (RLS)
-- See https://supabase.com/docs/guides/auth/row-level-security for more details.
alter table profiles enable row level security;

create policy "Public profiles are viewable by everyone." on profiles
  for select using (true);

create policy "Users can insert their own profile." on profiles
  for insert with check ((select auth.uid()) = id);

create policy "Users can update own profile." on profiles
  for update using ((select auth.uid()) = id);

-- This trigger automatically creates a profile entry when a new user signs up via Supabase Auth.
create function public.handle_new_user()
returns trigger as $$
begin
  insert into public.profiles (id, full_name, avatar_url)
  values (new.id, new.raw_user_meta_data->>'full_name', new.raw_user_meta_data->>'avatar_url');
  return new;
end;
$$ language plpgsql security definer;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

-- Set up Storage for Avatars
insert into storage.buckets (id, name)
  values ('avatars', 'avatars');

create policy "Avatar images are publicly accessible." on storage.objects
  for select using (bucket_id = 'avatars');

create policy "Anyone can upload an avatar." on storage.objects
  for insert with check (bucket_id = 'avatars');

-- 
-- Community Schema
--

create table groups (
  id bigint generated by default as identity primary key,
  name text not null,
  slug text unique not null,
  description text,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

create table posts (
  id bigint generated by default as identity primary key,
  title text not null,
  content text, -- could be markdown or html
  author_id uuid references profiles(id) not null,
  group_id bigint references groups(id),
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone,
  image_url text
);

create table comments (
  id bigint generated by default as identity primary key,
  post_id bigint references posts(id) on delete cascade not null,
  author_id uuid references profiles(id) not null,
  content text not null,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- RLS for Community
alter table groups enable row level security;
alter table posts enable row level security;
alter table comments enable row level security;

-- Groups are public read
create policy "Groups are viewable by everyone" on groups
  for select using (true);

-- Posts are public read
create policy "Posts are viewable by everyone" on posts
  for select using (true);

-- Authenticated users can create posts
create policy "Authenticated users can create posts" on posts
  for insert with check (auth.role() = 'authenticated');

-- Authors can update their own posts
create policy "Users can update own posts" on posts
  for update using (auth.uid() = author_id);

-- Authors can delete their own posts
create policy "Users can delete own posts" on posts
  for delete using (auth.uid() = author_id);

-- Admin Support (Optional: Run this to enable admin powers)
-- alter table profiles add column role text default 'user';
-- create policy "Admins can delete any post" on posts
--   for delete using ((select role from profiles where id = auth.uid()) = 'admin');

-- Comments are public read
create policy "Comments are viewable by everyone" on comments
  for select using (true);

-- Authenticated users can comment
create policy "Authenticated users can create comments" on comments
  for insert with check (auth.role() = 'authenticated');
