-- Create a table to track user owned items
create table if not exists user_inventory (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  item_id text not null,
  item_type text not null, -- 'badge' or 'effect'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Add badge slots to profiles
alter table profiles 
add column if not exists badge_left text default null,
add column if not exists badge_right text default null;

-- RLS Policies for user_inventory
alter table user_inventory enable row level security;

create policy "Users can view their own inventory" 
  on user_inventory for select 
  using ( auth.uid() = user_id );

create policy "Users can insert into their own inventory (via server action)" 
  on user_inventory for insert 
  with check ( auth.uid() = user_id );
