-- 0. Ensure Points and Active Effect columns exist (Missing from previous steps)
alter table profiles 
add column if not exists points integer default 0,
add column if not exists active_effect text default null;

-- 1. Create User Inventory & Badge Columns
create table if not exists user_inventory (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users(id) on delete cascade not null,
  item_id text not null,
  item_type text not null, -- 'badge' or 'effect'
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

alter table profiles 
add column if not exists badge_left text default null,
add column if not exists badge_right text default null;

-- Enable RLS for user_inventory
alter table user_inventory enable row level security;

-- Create policies if they don't exist (using DO block to avoid errors if policy exists)
do $$
begin
  if not exists (select from pg_policies where tablename = 'user_inventory' and policyname = 'Users can view their own inventory') then
    create policy "Users can view their own inventory" on user_inventory for select using ( auth.uid() = user_id );
  end if;
  
  if not exists (select from pg_policies where tablename = 'user_inventory' and policyname = 'Users can insert into their own inventory (via server action)') then
    create policy "Users can insert into their own inventory (via server action)" on user_inventory for insert with check ( auth.uid() = user_id );
  end if;
end
$$;

-- 2. Grant MAX POINTS to Admin (jundae54@gmail.com)
update profiles
set points = 999999
where id = (
  select id from auth.users where email = 'jundae54@gmail.com'
);
